version: '3.8'

services:
  clip-edit-tool:
    build: .
    ports:
      - "8247:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./public/videos:/app/public/videos
      - ./cookie.txt:/app/cookie.txt:ro
      - video_temp:/tmp/videos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  video_temp: